name: saint_mobile
description: "Modulo Android de facturación para el Saint Enterprise Administrativo"
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  dio: ^5.8.0+1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0 
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_blanco.png
    - assets/images/launcher_logo.png
    - assets/sql/schema.sql
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_logo.png"